[icons]
icons = "material-nf"

[[block]]
block = "music"
format = "{ $icon $combo.str(max_w:30,rot_interval:0.5) $prev $play $next |}"

[block.theme_overrides]
idle_bg = "#000000"
idle_fg = "#ffffff"
good_bg = "#ff6600"
good_fg = "#ffffff"
info_bg = "#ff6600"
info_fg = "#ffffff"

[[block]]
block = "custom"
command = "~/.config/i3/scripts/current-audio-output.sh"
interval = 3600

[[block]]
block = "sound"
format = " $icon $volume "
show_volume_when_muted = true

[[block]]
block = "memory"
format = "$icon $mem_used_percents "
interval = 5

[[block]]
block = "cpu"
format = "$icon $utilization "
interval = 2

[[block]]
block = "temperature"
format = " $icon $max "
chip = "k10temp-*"
interval = 5

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%Y-%m-%d %H:%M') "
interval = 60
